// Packs the Yale Bright Star Catalogue (5th revised edition, Hoffleit & Warren
// 1991, public domain) into src/scene/starCatalog.js: every star with a
// position, brightest first, as four little-endian uint16 per star:
// right ascension, declination (J2000), V magnitude and B-V colour index.
//
//   node scripts/build-stars.mjs [path/to/ybsc5]
//
// Without a path the catalogue is fetched from the Harvard-Smithsonian
// Telescope Data Center.
import { readFile, writeFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';

const SOURCE = 'http://tdc-www.harvard.edu/catalogs/ybsc5.gz';
const OUT = new URL('../src/scene/starCatalog.js', import.meta.url);

async function load(path) {
  if (path) return readFile(path, 'latin1');
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`${SOURCE}: ${res.status}`);
  return gunzipSync(Buffer.from(await res.arrayBuffer())).toString('latin1');
}

// Byte ranges are 1-based and inclusive, as in the catalogue's ReadMe.
const col = (line, a, b) => line.slice(a - 1, b).trim();

const text = await load(process.argv[2]);
const stars = [];
for (const line of text.split('\n')) {
  const hr = parseInt(col(line, 1, 4), 10);
  const raH = col(line, 76, 77);
  const vmag = col(line, 103, 107);
  // A handful of entries (novae and objects later found not to be stars)
  // carry no position or magnitude.
  if (!hr || raH === '' || vmag === '') continue;
  const ra = ((+raH + +col(line, 78, 79) / 60 + +col(line, 80, 83) / 3600) / 24) * 2 * Math.PI;
  const sign = col(line, 84, 84) === '-' ? -1 : 1;
  const dec = sign * (+col(line, 85, 86) + +col(line, 87, 88) / 60 + +col(line, 89, 90) / 3600) * (Math.PI / 180);
  const bvText = col(line, 110, 114);
  // No measured colour: assume a sun-like star.
  const bv = bvText === '' ? 0.65 : +bvText;
  stars.push({ hr, ra, dec, mag: +vmag, bv });
}
stars.sort((a, b) => a.mag - b.mag);

const buf = Buffer.alloc(stars.length * 8);
const clamp16 = (v) => Math.max(0, Math.min(65535, Math.round(v)));
stars.forEach((s, i) => {
  buf.writeUInt16LE(clamp16((s.ra / (2 * Math.PI)) * 65535), i * 8);
  buf.writeUInt16LE(clamp16(((s.dec + Math.PI / 2) / Math.PI) * 65535), i * 8 + 2);
  buf.writeUInt16LE(clamp16((s.mag + 2) * 1000), i * 8 + 4);
  buf.writeUInt16LE(clamp16((s.bv + 1) * 10000), i * 8 + 6);
});

const out = `// Generated by scripts/build-stars.mjs from the Yale Bright Star Catalogue,
// 5th revised edition (Hoffleit & Warren 1991, public domain). Do not edit.
// ${stars.length} stars, brightest first; per star four little-endian uint16:
// RA * 65535 / 2pi, (dec + pi/2) * 65535 / pi, (V + 2) * 1000, (B-V + 1) * 10000.
export const STAR_COUNT = ${stars.length};
export const STAR_DATA = '${buf.toString('base64')}';
`;
await writeFile(OUT, out);
console.log(`${stars.length} stars, V ${stars[0].mag} to ${stars[stars.length - 1].mag} -> ${OUT.pathname}`);
